name: build

on:
  push: {}
  pull_request: {}

jobs:
  Windows:
    runs-on: windows-latest
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      # - name: Install Dependencies
      #   shell: powershell
      #   run: |
      #     Invoke-WebRequest -Uri "https://github.com/org-Stupefy/Victoria/tree/master/thirdparty/premake/bin/premake5.exe" -OutFile premake5.exe
      #     Expand-Archive -Path premake5.exe

      # - name: Fix Projects
      #   shell: powershell
      #   run: |
      #     gci -recurse -filter "*.vcxproj" | ForEach-Object {
      #       (Get-Content $_.FullName) -Replace "<PlatformToolset>v110</PlatformToolset>","<PlatformToolset>v142</PlatformToolset>" | Set-Content -Path $_.FullName
      #       (Get-Content $_.FullName) -Replace "<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>","<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>" | Set-Content -Path $_.FullName
      #       (Get-Content $_.FullName) -Replace "<PlatformToolset>v140</PlatformToolset>","<PlatformToolset>v142</PlatformToolset>" | Set-Content -Path $_.FullName
      #       (Get-Content $_.FullName) -Replace "<WindowsTargetPlatformVersion>10.0.14393.0</WindowsTargetPlatformVersion>","<WindowsTargetPlatformVersion>10.0.18362.0</WindowsTargetPlatformVersion>" | Set-Content -Path $_.FullName
      #     }

      - name: Generating Dependencies
        shell: cmd
        run: |
          cd scripts
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          .\Win-GenProjects.bat /W4

      # - name: Building Glad
      #   shell: cmd
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/Glad/Glad.vcxproj /p:Platform=Win32 /p:Configuration=Release'

      # - name: Building GLFW
      #   shell: cmd
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/GLFW/GLFW.vcxproj /p:Platform=Win32 /p:Configuration=Release'

      # - name: Building ImGui
      #   shell: cmd
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/Victoria/thirdparty/imgui/ImGui.vcxproj /p:Platform=Win32 /p:Configuration=Release'

      # - name: Building Yaml-Cpp
      #   shell: cmd
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/Victoria/thirdparty/yaml-cpp/yaml-cpp.vcxproj /p:Platform=Win32 /p:Configuration=Release'

      # - name: Building Victoria
      #   shell: cmd
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/Victoria/Victoria.vcxproj /p:Platform=Win32 /p:Configuration=Release'

      - name: Building Sandbox
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Sandbox/Sandbox.vcxproj /p:Platform=Win32 /p:Configuration=Release'
