name: build

on:
  push: {}
  pull_request: {}

jobs:
  Windows:
    runs-on: windows-latest
    env:
      VS_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\
      MSBUILD_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      # - name: Install Dependencies
      #   shell: powershell
      #   run: |
      #     Invoke-WebRequest -Uri "https://github.com/org-Stupefy/Victoria/tree/master/thirdparty/premake/bin/premake5.exe" -OutFile premake5.exe
      #     Expand-Archive -Path premake5.exe

      - name: Generating Dependencies
        shell: cmd
        run: |
          cd scripts
          call "%VS_PATH%\VC\Auxiliary\Build\vcvars64.bat"
          .\Win-GenProjects.bat /W4

      - name: Building Glad
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/Glad/Glad.vcxproj /p:Platform=x64 /p:Configuration=Release'

      - name: Building GLFW
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/GLFW/GLFW.vcxproj /p:Platform=x64 /p:Configuration=Release'

      - name: Building ImGui
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/imgui/ImGui.vcxproj /p:Platform=x64 /p:Configuration=Release'

      - name: Building Yaml-Cpp
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/yaml-cpp/yaml-cpp.vcxproj /p:Platform=x64 /p:Configuration=Release'

      - name: Building Victoria
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/Victoria.vcxproj /p:Platform=x64 /p:Configuration=Release'

      - name: Building Sandbox
        shell: cmd
        run: '"%MSBUILD_PATH%\MSBuild.exe" Sandbox/Sandbox.vcxproj /p:Platform=x64 /p:Configuration=Release'

  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt install build-essential
          sudo apt install mingw-w64
          sudo apt install gcc g++ make -y
          sudo apt install libxcursor-dev -y
          sudo apt-get install libx11-dev -y
          sudo apt-get install libxi-dev -y
          sudo apt-get install libxrandr-dev -y
          sudo apt-get install libxinerama1 libxinerama-dev -y

      - name: Generating Dependencies
        run: |
          sh ./scripts/Linux-GenProjects.sh

      # - name: Building Glad
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/Glad/Glad.vcxproj /p:Platform=x64 /p:Configuration=Release'

      # - name: Building GLFW
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/GLFW/GLFW.vcxproj /p:Platform=x64 /p:Configuration=Release'

      # - name: Building ImGui
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/imgui/ImGui.vcxproj /p:Platform=x64 /p:Configuration=Release'

      # - name: Building Yaml-Cpp
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/thirdparty/yaml-cpp/yaml-cpp.vcxproj /p:Platform=x64 /p:Configuration=Release'

      # - name: Building Victoria
      #   run: '"%MSBUILD_PATH%\MSBuild.exe" Victoria/Victoria.vcxproj /p:Platform=x64 /p:Configuration=Release'

      - name: Building Sandbox
        run: make config=Release'

  # MacOS:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 1
  #         submodules: true

  #     - name: Install Dependencies
  #       run: |
  #         brew
